import {
  AppWindow,
  ArchiveX,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  CopyCheck,
  CreditCard,
  Inbox,
  Loader2,
  LockKeyhole,
  Menu,
  Palette,
  Plus,
  Search,
  Trash,
  X,
} from "lucide-react";

export const Icons = {
  add: Plus,
  app: AppWindow,
  billing: CreditCard,
  calendarClock: CalendarClock,
  check: Check,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  close: X,
  copy: Copy,
  copyChecked: CopyCheck,
  archive: ArchiveX,
  inbox: Inbox,
  menu: Menu,
  palette: Palette,
  privacy: LockKeyhole,
  search: Search,
  spinner: Loader2,
  trash: Trash,
};
