import { EMAIL_PROVIDER_LABELS } from "@skylar/parsers-and-types";

export const GMAIL_IMMUTABLE_LABELS: string[] = [
  EMAIL_PROVIDER_LABELS.GMAIL.SENT,
  EMAIL_PROVIDER_LABELS.GMAIL.DRAFT,
  EMAIL_PROVIDER_LABELS.GMAIL.CHAT,
];
