import {
  AppWindow,
  ArchiveRestore,
  ArchiveX,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  CopyCheck,
  CreditCard,
  File,
  FileVideo,
  FolderPlus,
  Forward,
  Inbox,
  Info,
  Layers3,
  Loader2,
  LockKeyhole,
  Mail,
  MailOpen,
  Menu,
  Palette,
  Paperclip,
  Plus,
  Reply,
  ReplyAll,
  Search,
  Trash,
  X,
} from "lucide-react";

export const Icons = {
  add: Plus,
  addLabel: FolderPlus,
  app: AppWindow,
  archive: ArchiveX,
  attachment: Paperclip,
  billing: CreditCard,
  calendarClock: CalendarClock,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  copy: Copy,
  copyChecked: CopyCheck,
  fileDefault: File,
  fileVideo: FileVideo,
  forward: Forward,
  inbox: Inbox,
  info: Info,
  markRead: MailOpen,
  markUnread: Mail,
  menu: Menu,
  palette: Palette,
  privacy: LockKeyhole,
  replyAll: ReplyAll,
  replySender: Reply,
  unarchive: ArchiveRestore,
  search: Search,
  senderActions: Layers3,
  spinner: Loader2,
  trash: Trash,
};
