export const GMAIL_MAX_BATCH_REQUEST_SIZE = 100;
export const GMAIL_MAX_MESSAGE_LIST_REQUEST_SIZE = 500;
export const GMAIL_MAX_HISTORY_LIST_REQUEST_SIZE = 500;
export const GMAIL_BATCH_SEPARATOR_PREFIX = "yellow_lemonades_";
