name: Deploy to prod
on:
  push:
    branches: ["main"]

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployApp:
    runs-on: ubuntu-latest
    # env:
    #Define your envs needed for static generation:
    # ENV_NAME: ${{ secrets.ENV_NAME }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::624006668369:role/GitHub
          role-duration-seconds: 14390 #adjust as needed for your build time
          aws-region: us-west-2
      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage prod
